### ISSUE TITLE
IllegalArgumentException: Error running RT inspection: path doesn't exist

### ISSUE THREAD

**Issue by drywolf** [idok/react-templates-plugin#10]
For most subdirectories in my Webstorm project the plugins works absolutely fine, but for some paths it gives the following exception and does not handle the grouping of .rt/.js files

Also no rt.js file is generated for the .rt file that has the problem to it.

```
Error running RT inspection: path doesn't exist
java.lang.IllegalArgumentException: path doesn't exist
    at com.wix.nodejs.NodeRunner.createCommandLine(NodeRunner.java:33)
    at com.wix.rt.cli.RTCliBuilder.createCommandLine(RTCliBuilder.java:34)
    at com.wix.rt.cli.RTCliBuilder.createCommandLineValidate(RTCliBuilder.java:56)
    at com.wix.rt.cli.RTRunner.compile(RTRunner.java:99)
    at com.wix.rt.inspection.RTExternalAnnotator.doAnnotate(RTExternalAnnotator.java:260)
    at com.wix.rt.inspection.RTExternalAnnotator.doAnnotate(RTExternalAnnotator.java:49)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass.d(ExternalToolPass.java:183)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:45)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:125)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
    at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
    at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
    at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
    at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
    at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
    at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

The full path on disk of the .rt file is "C:\ipp_main\Prototypes\Flux\Nexus-React-PrototypeApp\src\client\components\chart\ProtoChart.rt"

I have other .rt files in the same folder structure (i.e. under the "components" folder which work just fine)

**Comment by drywolf** [comment]
Turns out the path to the "rt" command executable was changed by another project member and committed to the SVN project repository, and that's what caused the error.

Is there any good way to specify the path to the rt executable as a path relative to the project root directory in .idea\reactTemplatesPlugin.xml ?
Currently this path is an absolute one and that lead to the problem described above.

**Comment by idok** [comment]
It is not recommended to keep .idea folder in source control

**Comment by drywolf** [comment]
Thanks for the hint ... actually everything in the .idea directory is recommended to be under version control, except for workspace.xml according to the [Jetbrains documentation](https://www.jetbrains.com/webstorm/help/directory-based-versioning-model.html).

I'm not sure how this guideline translates to custom plugins, but I guess one should 
- either put environment dependent plugin settings in a dedicated settings file, separated from plugin settings that should be shared with a team
- or use the existing workspace.xml to store such environment dependent plugin settings (just like in the first option, but reusing workspace.xml instead of an own separate file)
