### ISSUE TITLE
ClassCastException in plugin React-Templates 

### ISSUE THREAD

**Issue by alaindresse** [idok/react-templates-plugin#4]
Hi,

I'm getting repeated ClassCastExceptions with the plugin:

Error:
com.intellij.lang.javascript.psi.impl.JSFileImpl cannot be cast to com.intellij.psi.xml.XmlFile

Details:
com.intellij.lang.javascript.psi.impl.JSFileImpl cannot be cast to com.intellij.psi.xml.XmlFile
java.lang.ClassCastException: com.intellij.lang.javascript.psi.impl.JSFileImpl cannot be cast to com.intellij.psi.xml.XmlFile
    at com.wix.rt.codeInsight.RTTagDescriptorsProvider.getDescriptor(RTTagDescriptorsProvider.java:58)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.computeElementDescriptor(XmlTagImpl.java:456)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.getDescriptor(XmlTagImpl.java:441)
    at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider$2.getDescriptor(XmlEnumeratedValueReferenceProvider.java:93)
    at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider$2.getDescriptor(XmlEnumeratedValueReferenceProvider.java:89)
    at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider.getReferencesByElement(XmlEnumeratedValueReferenceProvider.java:58)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:124)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:70)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:56)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.getReferences(XmlTagImpl.java:192)
    at com.intellij.psi.impl.SharedPsiElementImplUtil.a(SharedPsiElementImplUtil.java:67)
    at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:49)
    at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:63)
    at com.intellij.psi.impl.PsiElementBase.findReferenceAt(PsiElementBase.java:87)
    at com.intellij.psi.SingleRootFileViewProvider.a(SingleRootFileViewProvider.java:415)
    at com.intellij.psi.SingleRootFileViewProvider.findReferenceAt(SingleRootFileViewProvider.java:387)
    at com.intellij.psi.impl.source.PsiFileImpl.findReferenceAt(PsiFileImpl.java:613)
    at com.intellij.codeInsight.TargetElementUtilBase.findReference(TargetElementUtilBase.java:116)
    at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:304)
    at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:95)
    at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:200)
    at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:60)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:88)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1146)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

java.lang.ClassCastException: com.intellij.lang.javascript.psi.impl.JSFileImpl cannot be cast to com.intellij.psi.xml.XmlFile
    at com.wix.rt.codeInsight.RTTagDescriptorsProvider.getDescriptor(RTTagDescriptorsProvider.java:58)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.computeElementDescriptor(XmlTagImpl.java:456)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.getDescriptor(XmlTagImpl.java:441)
    at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider$2.getDescriptor(XmlEnumeratedValueReferenceProvider.java:93)
    at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider$2.getDescriptor(XmlEnumeratedValueReferenceProvider.java:89)
    at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider.getReferencesByElement(XmlEnumeratedValueReferenceProvider.java:58)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:124)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:70)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:56)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.getReferences(XmlTagImpl.java:192)
    at com.intellij.psi.impl.SharedPsiElementImplUtil.a(SharedPsiElementImplUtil.java:67)
    at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:49)
    at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:63)
    at com.intellij.psi.impl.PsiElementBase.findReferenceAt(PsiElementBase.java:87)
    at com.intellij.psi.SingleRootFileViewProvider.a(SingleRootFileViewProvider.java:415)
    at com.intellij.psi.SingleRootFileViewProvider.findReferenceAt(SingleRootFileViewProvider.java:387)
    at com.intellij.psi.impl.source.PsiFileImpl.findReferenceAt(PsiFileImpl.java:613)
    at com.intellij.codeInsight.TargetElementUtilBase.findReference(TargetElementUtilBase.java:116)
    at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:304)
    at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:95)
    at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:200)
    at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:60)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:88)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1146)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

**Comment by idok** [comment]
Hi,
Please supply the following information:
1. IntelliJ IDE type and version
2. Operating system
3. Plugin version
4. When do you get the error
Thanks

**Comment by alaindresse** [comment]
Thanks for your reply.

I am using Idea 14.0.3 (trial version) on Linux Mint 17.1.

I had installed the previous version of your plugin, and got upgraded
within minutes. Errors occurred constantly in the background.
I have since _uninstalled and reinstalled the plugin, and no longer have
the errors_.

The creation of the test.rt.js now works, but I do have a remaining
question.
I created a test template file (test.rt) with the following content (taken
from your web site) :

<div>
    <h4 style="cursor:pointer" onClick="()=>this.toggle()">
        Click to {this.state.open ? 'close' : 'open'}
    </h4>
    <p rt-if="this.state.open">This is my paragraph. It opens and
        closes</p>
</div>

Intellij idea highlights as "expression statement is not assignment or
call" for the text highlighted in yellow above. Is that normal ?

Best regards,

Alain

## 

Alain Dresse
Bamboost http://www.bamboost.org CEO and co-founder
GSM: +32 478 403027

**Comment by alaindresse** [comment]
Hi,

I was a bit optimistic. I still get the error message every time I close a
.rt file.

Best regards,
Alain

## 

Alain Dresse
Bamboost http://www.bamboost.org CEO and co-founder
GSM: +32 478 403027

**Comment by idok** [comment]
Hi,
Regarding the warning highlight, this is a known issue, hopefully resolved in a future version.
Regarding the exception, I'll try to reproduce it.

**Comment by alaindresse** [comment]
Thanks !

Let me know if I can be of help.

Best regards,
Alain

## 

Alain Dresse
Bamboost http://www.bamboost.org CEO and co-founder
GSM: +32 478 403027

**Comment by idok** [comment]
the new version will be available soon

**Comment by alaindresse** [comment]
Thanks!

Sent from my IPad

Alain Dresse
BamBoost
GSM: +32 478 403027
